version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    versioning-strategy: lockfile-only
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
