language: python
dist: xenial
python:
  - "3.6"
  - "3.7"
env:
  global:
    - DATABASE_URL_TEST="postgres://postgres@localhost/test_solawi"
    - SECRET_KEY="hunter2"
services:
  - postgresql
install:
  - "pip install -r requirements.txt"
  - pip install codecov
before_script:
  - "createdb -U postgres test_solawi"
script:
  - "pytest --cov=./"
after_script:
  - codecov
