[project]
name = "csa-share-management"
version = "0.1.0"
description = "Small internal tool for managing monthly deposits in a community supported agriculture group"
authors = [{ name = "Knut Hühne", email = "knut@k-nut.eu" }]
requires-python = ">=3.10,<4"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "Flask",
    "Flask-Bcrypt",
    "Flask-Cors",
    "Flask-JWT-Extended",
    "Flask-Migrate",
    "Flask-SQLAlchemy",
    "psycopg2",
    "fints==5.0.0b1",
    "gevent",
    "gunicorn",
    "sentry-sdk[flask, sqlalchemy]",
    "python-dateutil",
    "Flask-Pydantic",
]

[tool.ruff]
line-length = 100
target-version = "py310"
extend-exclude = ["migrations"]

[dependency-groups]
dev = [
    "pytest",
    "factory-boy",
    "pytest-cov",
    "pytest-watch",
    "ruff",
]

[tool.ruff.lint]
select = ["E", "F", "I"] # Pyflakes (F), pycodestyle (E), isort (I)

[tool.uv]
package = false
default-groups = "all"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
