"""add new fields to share

Revision ID: 446bd5b15bf2
Revises: 1750dc339155
Create Date: 2017-07-12 07:57:56.842193

"""

# revision identifiers, used by Alembic.
revision = '446bd5b15bf2'
down_revision = '1750dc339155'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('share', sa.Column('archived', sa.Boolean(), nullable=True))
    op.add_column('share', sa.Column('email', sa.String(), nullable=True))
    op.add_column('share', sa.Column('note', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('share', 'note')
    op.drop_column('share', 'email')
    op.drop_column('share', 'archived')
    ### end Alembic commands ###
