"""empty message

Revision ID: 5cc85b66507f
Revises: c0de89fb178b
Create Date: 2017-04-10 07:52:28.331600

"""

# revision identifiers, used by Alembic.
revision = '5cc85b66507f'
down_revision = 'c0de89fb178b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('_password', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    ### end Alembic commands ###
