name: Pytest's test suite
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  pytest:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: solawi
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v7

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v7
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Setup uv
        uses: astral-sh/setup-uv@v7

      - run: |
          uv run flask db upgrade head
          uv run pytest --cov=./
        env:
          DATABASE_URL: postgresql://postgres:password@localhost/solawi
          DATABASE_URL_TEST: postgresql://postgres:password@localhost/solawi
          SECRET_KEY: required_but_unused_in_test
          FLASK_APP: solawi/app.py

      - run: uv run --with codecov codecov
